server:
  port: ${API_GATEWAY_PORT:7000}
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8762/eureka
    fetchRegistry: true
    registerWithEureka: true